routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Route::any('/form', 'Admin\FormController@index');
Route::any('/date_time_to_ajax', 'Admin\FormController@date_time_to_ajax');
Route::any('/date_time_from_ajax', 'Admin\FormController@date_time_from_ajax');
Route::post('/get-free-places-and-price', 'Admin\FormController@getPlacesAndPrice');
Route::post('/get-places-select', 'Admin\FormController@getPlacesSelect');
Route::post('/get-price', 'Admin\FormController@getPrice');
Route::post('/booking', 'Admin\FormController@booking');
Route::any('/order_bitein_dep_jatyr', 'Admin\FormController@order_bitein_dep_jatyr');

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Parkings
    Route::delete('parkings/destroy', 'ParkingController@massDestroy')->name('parkings.massDestroy');
    Route::resource('parkings', 'ParkingController');

    // Places
    Route::delete('places/destroy', 'PlaceController@massDestroy')->name('places.massDestroy');
    Route::resource('places', 'PlaceController');

    // Orders
    Route::delete('orders/destroy', 'OrderController@massDestroy')->name('orders.massDestroy');
    Route::resource('orders', 'OrderController');
    Route::any('/get-floors-to-edit', 'OrderController@get_floors');
    Route::any('/get-places-to-edit', 'OrderController@get_places');
    Route::post('/export-report', 'OrderController@download_report');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/Place.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;
use App\Order;

class Place extends Model
{
    use SoftDeletes;

    public $table = 'places';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    const STATUS_SELECT = [
        'on'  => 'В работе',
        'off' => 'Не работает',
    ];

    protected $fillable = [
        'floor',
        'place',
        'price',
        'parking_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function placeOrders()
    {
        return $this->hasMany(Order::class, 'place_id', 'id');
    }

    public function parking()
    {
        return $this->belongsTo(Parking::class, 'parking_id');
    }

    public function is_free($place_id, $date_from, $date_to){

        $orders_check_1 = Order::where('place_id', $place_id)
                            ->where('date_time_from', '>=', $date_from)
                            ->where('date_time_from', '<=', $date_to)
                            ->get();

        $orders_check_2 = Order::where('place_id', $place_id)
                            ->where('date_time_to', '>=', $date_from)
                            ->where('date_time_to', '<=', $date_to)
                            ->get();

        if($orders_check_2->count() > 0 || $orders_check_1->count() > 0){
            return false;
        }else{
            return true;
        }

    }
}

app/Http/Controllers/Admin/PlaceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyPlaceRequest;
use App\Http\Requests\StorePlaceRequest;
use App\Http\Requests\UpdatePlaceRequest;
use App\Parking;
use App\Place;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class PlaceController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('place_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $places = Place::all();

        $parkings = Parking::get();

        return view('admin.places.index', compact('places', 'parkings'));
    }

    public function create()
    {
        abort_if(Gate::denies('place_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parkings = Parking::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.places.create', compact('parkings'));
    }

    public function store(StorePlaceRequest $request)
    {
        $place = Place::create($request->all());

        return redirect()->route('admin.places.index');
    }

    public function edit(Place $place)
    {
        abort_if(Gate::denies('place_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $parkings = Parking::all()->pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $place->load('parking');

        return view('admin.places.edit', compact('parkings', 'place'));
    }

    public function update(UpdatePlaceRequest $request, Place $place)
    {
        $place->update($request->all());

        return redirect()->route('admin.places.index');
    }

    public function show(Place $place)
    {
        abort_if(Gate::denies('place_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $place->load('parking', 'placeOrders');

        return view('admin.places.show', compact('place'));
    }

    public function destroy(Place $place)
    {
        abort_if(Gate::denies('place_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $place->delete();

        return back();
    }

    public function massDestroy(MassDestroyPlaceRequest $request)
    {
        Place::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/places/relationships/placeOrders.blade.php
<div class="m-3">
    @can('order_create')
        <div style="margin-bottom: 10px;" class="row">
            <div class="col-lg-12">
                <a class="btn btn-success" href="{{ route('admin.orders.create') }}">
                    {{ trans('global.add') }} {{ trans('cruds.order.title_singular') }}
                </a>
            </div>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            {{ trans('cruds.order.title_singular') }} {{ trans('global.list') }}
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-placeOrders">
                    <thead>
                        <tr>
                            <th width="10">

                            </th>
                            <th>
                                {{ trans('cruds.order.fields.id') }}
                            </th>
                            <th>
                                {{ trans('cruds.order.fields.date_time_from') }}
                            </th>
                            <th>
                                {{ trans('cruds.order.fields.date_time_to') }}
                            </th>
                            <th>
                                {{ trans('cruds.order.fields.name') }}
                            </th>
                            <th>
                                {{ trans('cruds.order.fields.phone') }}
                            </th>
                            <th>
                                {{ trans('cruds.order.fields.car_num') }}
                            </th>
                            <th>
                                {{ trans('cruds.order.fields.email') }}
                            </th>
                            <th>
                                {{ trans('cruds.order.fields.status') }}
                            </th>
                            <th>
                                {{ trans('cruds.order.fields.place') }}
                            </th>
                            <th>
                                &nbsp;
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($orders as $key => $order)
                            <tr data-entry-id="{{ $order->id }}">
                                <td>

                                </td>
                                <td>
                                    {{ $order->id ?? '' }}
                                </td>
                                <td>
                                    {{ $order->date_time_from ?? '' }}
                                </td>
                                <td>
                                    {{ $order->date_time_to ?? '' }}
                                </td>
                                <td>
                                    {{ $order->name ?? '' }}
                                </td>
                                <td>
                                    {{ $order->phone ?? '' }}
                                </td>
                                <td>
                                    {{ $order->car_num ?? '' }}
                                </td>
                                <td>
                                    {{ $order->email ?? '' }}
                                </td>
                                <td>
                                    {{ App\Order::STATUS_SELECT[$order->status] ?? '' }}
                                </td>
                                <td>
                                    {{ $order->place->place ?? '' }}
                                </td>
                                <td>
                                    @can('order_show')
                                        <a class="btn btn-xs btn-primary" href="{{ route('admin.orders.show', $order->id) }}">
                                            {{ trans('global.view') }}
                                        </a>
                                    @endcan

                                    @can('order_edit')
                                        <a class="btn btn-xs btn-info" href="{{ route('admin.orders.edit', $order->id) }}">
                                            {{ trans('global.edit') }}
                                        </a>
                                    @endcan

                                    @can('order_delete')
                                        <form action="{{ route('admin.orders.destroy', $order->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                        </form>
                                    @endcan

                                </td>

                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('order_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.orders.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-placeOrders:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection